import { Routes } from '@angular/router';
import { authGuard } from './layout/global/guard/auth.guard';
import { NotFoundComponent } from './layout/pages/not-found/not-found.component';


export const routes: Routes = [
    {path:'',redirectTo:'login',pathMatch:'full'},
    {path:'home',
        loadComponent:()=>import('./layout/pages/home/home.component').then((load)=>load.HomeComponent),
        canActivate:[authGuard]},
    {path:'brands',
        loadComponent:()=>import('./layout/pages/brands/brands.component').then((load)=>load.BrandsComponent),
        canActivate:[authGuard]},
    {path:'cart',
        loadComponent:()=>import('./layout/pages/cart/cart.component').then((load)=>load.CartComponent),
        canActivate:[authGuard]},
    {path:'wish list',
        loadComponent:()=>import('./layout/pages/wishlist/wishlist.component').then((load)=>load.WishlistComponent),
        canActivate:[authGuard]},
    {path:'order/:id',
        loadComponent:()=>import('./layout/pages/order/order.component').then((load)=>load.OrderComponent),
        canActivate:[authGuard]},
    {path:'allorders',
        loadComponent:()=>import('./layout/pages/allorders/allorders.component').then((load)=>load.AllordersComponent),
        canActivate:[authGuard]},
    {path:'categories',
        loadComponent:()=>import('./layout/pages/categories/categories.component').then((load)=>load.CategoriesComponent),
        canActivate:[authGuard]},
    {path:'products',
        loadComponent:()=>import('./layout/pages/products/products.component').then((load)=>load.ProductsComponent),
        canActivate:[authGuard]},
    {path:'product-detalis/:id',
        loadComponent:()=>import('./layout/pages/product-detalis/product-detalis.component').then((load)=>load.ProductDetalisComponent),
        canActivate:[authGuard]},
    {path:'register',
        loadComponent:()=>import('./layout/pages/register/register.component').then((load)=>load.RegisterComponent)},
    {path:'forgetpassword',
        loadComponent:()=>import('./layout/pages/forgetpassword/forgetpassword.component').then((load)=>load.ForgetpasswordComponent)},
    {path:'login',
        loadComponent:()=>import('./layout/pages/login/login.component').then((load)=>load.LoginComponent)},
    {path:'**',component:NotFoundComponent},
];
